server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  webuni:
    tokenlib:
      keypaths:        
        public: /Users/atschweger/Downloads/public.pem
