server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  webuni:
    tokenlib:
      keypaths:
        private: /Users/atschweger/Downloads/private.pem
        public: /Users/atschweger/Downloads/public.pem